OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Hospital1
    Domain: medplace1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Hospital2
    Domain: medplace2.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1