# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.medplace1.example.com:
    container_name: peer0.medplace1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.medplace1.example.com
      - CORE_PEER_ADDRESS=peer0.medplace1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.medplace1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.medplace1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.medplace1.example.com:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/medplace1.example.com/peers/peer0.medplace1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/medplace1.example.com/peers/peer0.medplace1.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.medplace1.example.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.medplace2.example.com:
    container_name: peer0.medplace2.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.medplace2.example.com
      - CORE_PEER_ADDRESS=peer0.medplace2.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.medplace2.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.medplace2.example.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.medplace2.example.com:8051
      - CORE_PEER_LOCALMSPID=Hospital2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/medplace2.example.com/peers/peer0.medplace2.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/medplace2.example.com/peers/peer0.medplace2.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.medplace2.example.com:/var/hyperledger/production
    ports:
      - 8051:8051

  caHospital1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hospital1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.medplace1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/medplace1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  caHospital2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hospital2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.medplace2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/cfa8808572669aff3f154ba8380f8b6e3f127ad2162bad56601752ef079f7f6f_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/medplace2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

